### ISSUE TITLE
How to download/use?

### ISSUE THREAD

**Issue by Semichaotic** [TochigiV/Inject#1]
Question in title

**Comment by TochigiV** [comment]
is it seriously that hard

**Comment by Semichaotic** [comment]
Yes XD

2017-06-04 1:12 GMT+02:00 Tochigi <notifications@github.com>:

**Comment by TochigiV** [comment]
![screen shot 2017-06-08 at 2 08 36 pm](https://user-images.githubusercontent.com/7752021/26943564-0487a3b0-4c54-11e7-8941-2ccb516b9630.png)
